{
  "name": "async-try-loader",
  "version": "1.1.0",
  "description": "将所有async与await用try catch包裹",
  "main": "src/main.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "wanghy",
  "license": "ISC",
  "devDependencies": {
    "@babel/core": "^7.5.0",
    "@babel/parser": "^7.5.0",
    "@babel/preset-env": "^7.5.2",
    "@babel/traverse": "^7.5.0",
    "@babel/types": "^7.5.0",
    "babel-jest": "^24.8.0",
    "babel-polyfill": "^6.26.0",
    "eslint": "^6.1.0",
    "eslint-config-prettier": "^6.0.0",
    "eslint-plugin-prettier": "^3.1.0",
    "husky": "^2.6.0",
    "jest": "^24.8.0",
    "lint-staged": "^9.2.1",
    "loader-utils": "^1.2.3",
    "memory-fs": "^0.4.1",
    "prettier": "^1.18.2",
    "webpack": "^4.35.3"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged && npm run test"
    }
  },
  "lint-staged": {
    "*.{js}": [
      "eslint --fix"
    ]
  },
  "dependencies": {
    "babel-template": "^6.26.0"
  }
}
